### ISSUE TITLE
create Alkalinity subroutine

### ISSUE THREAD

**Issue by CodySpradling** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#12]

**Comment by jkr32** [comment]
http://tillamookchc.org/wp-content/uploads/2016/06/HowToCalcChemNeededToAdjPoolChem.pdf

Formula would be: 
Chemical Dosage = pool Factor X Change Factor X 1.5 lbs sod. bicarb.

The webpage above breaks down each of the main factors
-chemical dosage
-pool factor
-change factor
-sod. bicarb
Since each pools volume is difference, and desired levels are different the formula would change accordingly.
