### ISSUE TITLE
create hardness subroutine

### ISSUE THREAD

**Issue by CodySpradling** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#14]

**Comment by DKlesel** [comment]
This issue, as well as the other subroutine issues are dependent upon the formulas issue being completed first.

**Comment by leoschuster** [comment]
So- I didn’t read the issues completely before I started working on them (I shouldn’t have done the actually coding). After several hours of work, I created one .cpp file coding C++ in CodeBlocks. I didn’t do Java because I still need to learn it and it would take too long to code for me personally for the 1st sprint.

My formulas and equations are in comments above their respective subroutines. I added a subroutine to this sprint- one that calculates the size of the pool in gallons. Most of these subroutines only calculates needed chemicals for a pool filled with new water. The .cpp file has subroutines for pool size, pH, chlorine, and hardness. I did not work on Alkalinity or Cyanic Acid. The program runs fine on my computer. Let me know if it doesn’t work so we can figure something out!

You can navigate to Leo’s Research Branch and I called the .cpp file poolVersion1.

I had another thought: should we implement a typing method for our users to punch in information or use a slider method (finger+phone screen)?

Resources:
http://www.pahlen.com/users-guide/ph-and-chlorine
http://homeguides.sfgate.com/amount-chlorine-use-per-gallon-pool-water-89184.html
http://www.doityourself.com/stry/how-to-raise-swimming-pool-ph
http://www.lesliespool.com/Leslies-Dry-Acid-Buckets/Dry-Acid.htm
https://www.hayward-pool.com/shop/en/pools/water-chemistry-calculator
https://www.taylortechnologies.com/ChemistryTopicsCM.ASP?ContentID=70
http://www.livestrong.com/article/187953-how-do-i-add-calcium-chloride-to-a-pool/

![where to find the cpp file](https://cloud.githubusercontent.com/assets/25251382/23324066/4916a066-fab1-11e6-9da9-bcc53e28fa02.jpg)
