### ISSUE TITLE
Make a hello world app and try to run it / emulate it 

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#16]

**Comment by leoschuster** [comment]
Where I started: https://developer.android.com/training/basics/firstapp/index.html

**Comment by leoschuster** [comment]
NOTE: Under System Image, I downloaded Lollipop x86_64 and HAXM (Lollipop because that is what we discussed as a team in class). I had to enable VT-x in my computer’s BIOS (I looked up Google and YouTube videos to figure this out).

I went through the Tutorial and completed the entire “Building Your First App” section. It took me 2 hours to complete. I wasn’t able to download GitHub desktop on my new laptop, so I will upload my Android Studio App on GitHub later when I am not on school’s wifi.
![20170217_093107_resized](https://cloud.githubusercontent.com/assets/25251382/23074824/cc733eb8-f4ff-11e6-9998-dd0a60c8f84f.jpg)
![screenshot_1487345993](https://cloud.githubusercontent.com/assets/25251382/23074831/d0d2f688-f4ff-11e6-9381-0c657fb03fe6.png)

**Comment by jkr32** [comment]
I followed Leo's same instructions and took a screenshot of my end results. That walk through made it very clear and simple. 

<img width="311" alt="helloworld" src="https://cloud.githubusercontent.com/assets/22899987/23144250/e11073ca-f78b-11e6-9327-e59272a5cd48.png">

**Comment by ntw8** [comment]
![image](https://cloud.githubusercontent.com/assets/25353809/23181582/1c103348-f83b-11e6-80aa-8045afa74a66.png)

![image](https://cloud.githubusercontent.com/assets/25353809/23181632/51968ba2-f83b-11e6-8a0a-9f1a50516681.png)

This is my App's main code (I believe) and a picture of the emulator running the app.

**Comment by CodySpradling** [comment]
![image](https://cloud.githubusercontent.com/assets/25287736/23197716/ce38b4b8-f887-11e6-82cd-19b5de2cd45b.png)

**Comment by dms187** [comment]
Sorry it took longer than intended. Blocks from academic obligations and hardware complications delayed me for an unexpectedly long time.
![hello_world_app_duncan](https://cloud.githubusercontent.com/assets/25291747/23238049/baa1e8ae-f925-11e6-9734-2d77da13839f.png)
