### ISSUE TITLE
Do the research - find the pros and cons and present which language you would like to use to the team. 

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#18]

**Comment by leoschuster** [comment]
Can every team member please look through my provided links and see if we should use C++ or another language please? (Reading through my links should count towards your own research time). I say **YES** to C++ only because every team member knows it but there are arguments for doing it in Java.

I have spent 1 hour researching on this issue.

**Pros for C++:**
-> Android Studio has built in C++ support. “Android Studio knows not all code is written in Java and not all code runs on the user's device. Android Studio fully supports editing C/C++ project files so you can quickly build JNI components in your app. The IDE provides syntax highlighting and refactoring for C/C++, and an LLDB-based debugger that allows you to simultaneously debug your Java and C/C++ code. The build tools can also execute your CMake and ndk-build scripts without any modification and then add the shared objects to your APK” [1].
-> When you start creating a new app, the dialog box gives you an option to toggle “C++ Support”.
-> Cody, Duncan, Nick, Calum, John, and I are all proficient in C++ according to our responses in Assignment 7. That is everyone in the team! That means we can all look at and edit C++ code.
-> Helpful link in Android Studio’s User Guide about their C++ support [2].
-> Stack Overflow forums have a page on how to get started [3].
-> An article about reasons to use C++ for Android development [4].

**Cons:**
-> Cody, Duncan, and Nick are somewhat proficient in Java. Only three people would be somewhat familiar while the other three are starting from new.
-> Article about reasons to not use C++ for Android development [5]. 
Highlights: “Think of it this way. You have the ability using the Java SDK to build a full working application that takes advantage of 100% of the APIs available to developers. There is nothing you can do with the NDK that cannot be done with the SDK (from an API perspective), the NDK just provides higher performance.
Now look at it in reverse. If you choose to write an application 100% in the NDK, you can still write a fully functional application, but you are limited in the number of framework APIs you can access. Not all of the Android framework can be accessed at the native layer; most APIs are Java only. That's not to say that all the APIs YOU may need aren't available in the NDK, but nowhere near ALL the APIs are exposed [5]”

**Sources:**
[1] https://developer.android.com/studio/features.html
[2] https://developer.android.com/studio/projects/add-native-code.html
[3] http://stackoverflow.com/questions/32150500/how-to-get-started-with-android-studio-c-development
[4] http://insights.dice.com/2016/02/03/5-reasons-to-use-c-for-android-development/
[5] http://stackoverflow.com/questions/13773686/why-shouldnt-an-android-app-be-written-in-c-c-because-you-simply-prefer-to-p

**Comment by DKlesel** [comment]
I posted my arguments in the Wiki on the repository. I think it might be a good idea to post our docs there so that we can keep track of all the research and frameworks we do there. Please look over what Leo and I have posted and include your research and votes as well. Thanks
