### ISSUE TITLE
Create the UML diagram that the whole team can read and understand and upload the file to GitHub

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#24]

**Comment by leoschuster** [comment]
I started with a blank legal-sized paper. I hand-drew the first draft of the UML diagram. I then transferred it to http://www.draw.io so that anybody can open and edit the UML diagram file. The diagram took me 1 hr 40 min to create and figure out.

![20170217_141721_resized](https://cloud.githubusercontent.com/assets/25251382/23083598/0f3ec842-f524-11e6-8396-96f870054c25.jpg)
https://www.draw.io/?chrome=0&lightbox=1&highlight=0000ff&edit=_blank&layers=1&title=UML%20Diagram%20Tiger%20Pool%20Boy%20(2).xml#R7Vxrc9soFP01nul2Jh09rIc%2F2k76mEnazKa7234kFra1lYRXwkm8v34BgYRAauzEFqpnO5mpBAihcw%2BXA1w8cufp04ccbNY3KILJyLGip5F7OXIc23Zc8h9N2ZUpvu2XCas8jnihOuEu%2FhfyRIunbuMIFo2CGKEEx5tm4gJlGVzgRhrIc%2FTYLLZESfOtG7CCWsLdAiR66l9xhNfiuyyrzvgI49Wavzr0eMY9WPxY5Wib8feNHHfJ%2FpXZKRB18fLFGkToUUpyr0buPEcIl1fp0xwmFFsBm3gO70RbR%2B5sjdOE3NjkkmW%2F73jY3udh8nE5zLD8uq76PFerEEYESH6LcrxGK5SB5KpOnTF0IK3Bar4dPsX4G01%2B5%2FG77yInw%2FlOyqK333kFf0OMd5xBYIsRSarfe43QpvPbBBpomy946x3ONZCvIC%2FFP5F%2Bl%2FQYx%2BMDRCkkjSEFcpgAHD80CQQ4D1dVuRpNcsEBbQeXt%2BUBJFthLMdPSKtmS0Q%2BQUbd%2F2eLRMZFwbCYkgKuv3mqM8nViv7%2FRwFzURNpQ1lZmaVZ83EdY3i3AQyfR9LXSaEC5%2BhH1S3c5xjEkXiAOYZPP0WQ5445xXfN20epH4pesJa6oG%2B9HnJvfGZ8dnU%2Be6b47Gp8nmZRjki2Y92uUQaHyD67T%2Fr5wSnoZ0vkk%2Fj2jT9Rk4%2FlHZV%2BY51%2Btm2Kf4E%2B%2Bv3anbsNXccYuucmBdrQNaYFxprvvAFxRlJuYLYdhN90fcVxWn2O296Zkc%2FTyRea4p4Xntmo1AJuYAxcrWN%2FjVdUn1u1cL8lM1%2BSMEM7Wcxb081mED1fUUz9CvbJmXX8oGXUsYyN6Ro5r9GKDTt3ixzCbBD0cyyD%2FPP15Zhf2zeGQ%2BJfqPFvnkOAIZ0w5mgZJ%2FTqzTLOC7ocguOU3m8L%2BNsgiKn4RbdXXvY01zkq9wTRGuSbmCKf7%2FQ%2FtISuOriwm1uYE25jIgtOMOK0oe4Y6%2FL%2BSaaRBh1qG7xjU%2BiKxkgetXKkA%2FCY6lDer8s8t2mOWGlrdGxjq2%2BiNRL1LgEGJIVoSjbjGQABPdfgIkZwbnMZsRjZmGgb234ITyLVhwavbwzekyjOn7lPE%2FAaW4QTrZHc558o2bIZzxwkiy15HxqGE1VXgivV0YcTDU%2Bj2g3SsGUL1xwNQ%2F%2FcnGgLvKG5MeokGnRg8AbGFtttPQRhvoZpvAC01CUqaFTY4Pxp6Br0p2L9pbEGDKJBAKMGCvk94uLoM%2Bk78DCMabQ9MQhMcG4r4lX8qTyNdky5sIoNNe8%2BLYfns%2FyJwYm0sI681BAXmwTsRNhjFD%2BIkMdLtp9A6rS%2Bsv0DdoUwHRGqEEmp%2BCDQDU3GWox1z3doXKozbotLFbXEVaDqzTUdlmOwykFKrtCSWancHm9sigtDxWpdz8W3EsBx0zwgiVcZuV4Q89AFd9Z24b1oAWomqhimvGAaRxFzYgUhQZytruESc6vzlN%2B5AdyKGnOUILqYn9GoR%2Br%2BMMDgnr2CurMNijPMTOTNyB8BfE4dm3dJ6enN7Pqe%2FNHiOZ6jjFQNYsYpCAr8CAt8HLa5YZNtnk62sIVrjn8ErunhES1d%2BFD62WEb%2Fa6imD5NJKJVFvsMqD%2Fo4FG7bzht05zXN%2B0o7bCrdlxDRNv1zg5GY5LsTl3r9ub%2Fvne8vhcESt9z%2B%2Bt7PSxHV9rNUGiNubCvvlWyPTqtSm6JqTO2iuLr0bI62lk0pefEyN19ghY%2FGDzR%2BzgRmMrwPmsZ4bgS5n80N4UplrWV3lnEX9aWurCkBHWr%2FxDwn0WaOxXywtAbuw3HciH25%2Fa2Bq%2F%2BlvpLae6piAU7UCRn2W7%2BVG1TrSItnthVKiqpplVErEp1flWM%2B%2FPuBiszFced%2FLRdannxgZ3foR4oObS82yhPLsovVJ4Wn4uWywLikdpbKhLs14F02aXv7uSQyAVp4GwZxzu6wz3CGKUkIwH3MJlVJybFyFyfmeQKoPRRdnt%2FEL2dHwXlLRrVKzR7D7YXh3aBvR2S3yljiUzJWgXZogSDqqx8df%2FGopqLTU6lq9%2BYEKOxwEy%2BLUEaJ7vyGVIRSDcs03XH1DwweYDUDFpOsxJJA9pUAzbyylbSzAzlKVs1lbIfuQJpyU%2FIWAPzCy7KWotQOXjBmTNljyxxMzMmo1%2FG67ektrFMIsCyYkmqFJXT82S8AJujs5dXrWcz9Sof5VGzbXL19ZHeC8Uo7NwBN4ZyXZsm4ksP7Kk4S2KpYcsEASw3WFXcn6m%2BTnjQbZxuEphSbRxJGrtk0N4a%2BwiitFqAFi6qZUbotahS1YO%2FaHlRd03dazs1nldsQkFJla1IE2Wc957IKVXxLztGVfeggM9XNICFJ3VQdh3d8qdbWda96Kdss8UtEGfb9FpYej%2BjkCc%2BCoPu%2FcSstNtQreXZJq2lHx7ostaC78HNUbE%2F%2FOKhaUo8c%2BdjA7DCJDBohUnLzOeX3lAOWg4ohMbiaSfndui1FV5jp14n53assw3eiTH2Bvr5Gr6rMrTdRJOyI9SDRtiO65cNzIk90DBOwakQjfsMnQ%2F1Bbc72DbSf96m9t4jPCnsHFLY3buwZLrBygbPeqFB1QW3Fxn0dbOsRR1UtSg13evnSFKdQEi%2B4U%2BY1Nitfj1X3z8nc%2BpNhrZoQnO%2FyTE5CbwG1YlQIg11YuxAwUQfVL5sMZtBDqFjhwbH24m%2BEtLtnocezDRRVimqM1i9IKlL4BIv95JqlbelBhkASoGi77ygT5T0IGDOKovdWRVWb0sdNgDAPDVyok%2FAqoA8U2PD0c%2Fmh23nJIwNvbalh8GK41AK7BKMnfuQrcEA3YPuiwET%2FehZwFrCe165Lx8o28qep9B87315xV1Xkb7P7Mu%2FYBvatjrPaxzNzFXPCg6RXS9nwL4ntwTayvzB%2F0nw5f5k6Kz1YDIoFQX2schAbusfQS6L17807V79Bw%3D%3D

**Comment by DKlesel** [comment]
In order for us to move any more forward with this UML diagram we will need some of the other tasks completed. For example, we definitely need the features task completed so that we can see what features classes we might need. I can work more on this once that is finished. I will talk about this in the stand up today.

**Comment by DKlesel** [comment]
I committed a PDF of the high level design of the code as it might look by the end of sprint one here: https://github.com/CS3398-Tiger-Terrors/Research/blob/Master/PoolBoy%20UML.pdf

Here is another copy for reference: 
[PoolBoy UML.pdf](https://github.com/CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017/files/802251/PoolBoy.UML.pdf)

I spent approximately 2 hours working on this.
