### ISSUE TITLE
As a developer I would like to know the formulas/math that we will need to implement so that the app can CALKULAT

### ISSUE THREAD

**Issue by DKlesel** [CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017#9]
Create a spreadsheet that names and shows the formulas that we will need to implement into the app.

**Comment by leoschuster** [comment]
Status for standup: I am planning on working on this once Issue #17 is finalized. I will make a document with all the formulas and mathematical equations we need to make our app be a calculator.

**Comment by leoschuster** [comment]
So- I didn’t read the issues completely before I started working on them (I shouldn’t have done the actually coding). After several hours of work, I created one .cpp file coding C++ in CodeBlocks. I didn’t do Java because I still need to learn it and it would take too long to code for me personally for the 1st sprint.

My formulas and equations are in comments above their respective subroutines. I added a subroutine to this sprint- one that calculates the size of the pool in gallons. Most of these subroutines only calculates needed chemicals for a pool filled with new water. The .cpp file has subroutines for pool size, pH, chlorine, and hardness. I did not work on Alkalinity or Cyanic Acid. The program runs fine on my computer. Let me know if it doesn’t work so we can figure something out!

You can navigate to Leo’s Research Branch and I called the .cpp file poolVersion1.

I had another thought: should we implement a typing method for our users to punch in information or use a slider method (finger+phone screen)?

Resources:
http://www.pahlen.com/users-guide/ph-and-chlorine
http://homeguides.sfgate.com/amount-chlorine-use-per-gallon-pool-water-89184.html
http://www.doityourself.com/stry/how-to-raise-swimming-pool-ph
http://www.lesliespool.com/Leslies-Dry-Acid-Buckets/Dry-Acid.htm
https://www.hayward-pool.com/shop/en/pools/water-chemistry-calculator
https://www.taylortechnologies.com/ChemistryTopicsCM.ASP?ContentID=70
http://www.livestrong.com/article/187953-how-do-i-add-calcium-chloride-to-a-pool/

![where to find the cpp file](https://cloud.githubusercontent.com/assets/25251382/23324066/4916a066-fab1-11e6-9da9-bcc53e28fa02.jpg)

**Comment by DKlesel** [comment]
Okay so the issue I'm running into here is I need to know the following items in order to implement anything in the code. Someone, please tell me the answers to the following questions:
1. What is the target hardness level?
2. What is the target chlorine level and what chemical should we base our calculations off of? we can implement other chemicals later on, but for now lets stick with one because it will require a bunch of extra code in order implement all the other chemicals.
3. What is the target alkalinity? As with chlorine, which chemical to base the calculations off of?
4. What is the target cyanuric acid?
5. Is there a target pH, or should I just calculate based off the image here?https://raw.githubusercontent.com/CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017/Images-for-chem-calc's/IMG_20170221_191303.jpg
- I've already made the code for it to calculate based on that image, but we can change this later. 

Someone please answer me here. Thanks!

@leoschuster @CodySpradling @jkr32 @dms187 @ntw8

**Comment by leoschuster** [comment]
I've included the formulas and range I used in my .cpp file. I don't know alkalinity or cyanuric acid.

**Comment by DKlesel** [comment]
@leoschuster all your function for chlorine does is move the chlorine up by 1 ppm. I see that you said it should be between 1 and 3 ppm but if we are going to recommend a dosage then we should have a set number to get it at every time. We could do something that checks if it is between 1 & 3 and then make a recommendation on dosage to get it back to that range. However, still need to know what chemicals to use for chlorine, each chemical has a different level of effectiveness as you can see here: https://raw.githubusercontent.com/CS3398-Tiger-Terrors/CS3398-Tiger-Terrors-S2017/Images-for-chem-calc's/IMG_20170221_191303.jpg
As for the pH, I got that one coded already to get it up or down to the levels in the picture above. As it is now it gets the ph up to 7.4 if it is below that amount and it gets it lower from a higher level just from what that chart shows for soda ash. However, we still need to decide on if we are going to do this for all the chemicals or just for one or two. 
So yeah we still need to figure these out and make a decision for us to be able to move forward with anything.

**Comment by DKlesel** [comment]
@CodySpradling I think since your the pool expert we need some guidance from you on this. lol
